[package]
name = "matasano-rust"
version = "0.1.0"
authors = ["Matthew Burke <matthewpatrickburke@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hex="0.4.2"
base64="0.12.3"